[package]
name = "threecast"
version = "0.1.0"
authors = ["Bradley Gannon <bradley@bradleygannon.com>"]
edition = "2018"

[dependencies]
bzip2-rs = "0.1.2"
chrono = "0.4.19"
clap = "2.34.0"
reqwest = { version = "0.11.7", features = ["blocking"] }
