[package]
name = "threecast-data-tool"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Bradley Gannon <bradley@bradleygannon.com>"]
edition = "2021"

[[bin]]
name = "tcdt"
path = "src/main.rs"

[dependencies]
chrono = "0.4.19"
clap = "2.34.0"
threecast = { path = "../threecast" }
