[package]
name = "threecast-cli"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Bradley Gannon <bradley@bradleygannon.com>"]
edition = "2021"

[dependencies]
clap = "2.34.0"
threecast = { path = "../threecast" }
